"""
Writer.com AI detector implementation
"""

from playwright.sync_api import Page
import time
import re
from .base_detector import BaseDetector


class WriterDetector(BaseDetector):
    """Writer.com AI content detector"""
    
    @property
    def name(self) -> str:
        return "writer"
    
    @property
    def url(self) -> str:
        return self.config['detectors']['writer']['url']
    
    def _submit_text(self, page: Page, text: str):
        """Submit text to Writer.com"""
        try:
            # Wait for textarea
            page.wait_for_selector('textarea, [contenteditable="true"]', timeout=10000)
            
            # Try textarea first
            textarea = page.query_selector('textarea')
            if textarea:
                textarea.fill(text)
            else:
                # Try contenteditable div
                editable = page.query_selector('[contenteditable="true"]')
                if editable:
                    editable.fill(text)
            
            # Look for submit button
            button_selectors = [
                'button:has-text("Analyze")',
                'button:has-text("Check")',
                'button:has-text("Detect")',
                'button[type="submit"]'
            ]
            
            for selector in button_selectors:
                try:
                    button = page.query_selector(selector)
                    if button:
                        button.click()
                        time.sleep(5)
                        break
                except:
                    continue
                    
        except Exception as e:
            raise Exception(f"Error submitting text to Writer: {e}")
    
    def _extract_result(self, page: Page) -> float:
        """Extract AI detection percentage from Writer.com"""
        try:
            # Wait for results
            page.wait_for_load_state('networkidle')
            time.sleep(3)
            
            content = page.content()
            
            # Writer.com shows results in various formats
            patterns = [
                r'(\d+)%\s*(?:human|AI|generated)',
                r'score.*?(\d+)%',
                r'(\d+(?:\.\d+)?)\s*%'
            ]
            
            percentages = []
            for pattern in patterns:
                matches = re.findall(pattern, content, re.IGNORECASE)
                for match in matches:
                    try:
                        val = float(match)
                        if 0 <= val <= 100:
                            percentages.append(val)
                    except:
                        continue
            
            if percentages:
                # Return the highest percentage (likely the AI score)
                return max(percentages)
            
            # Fallback: look for text indicators
            content_lower = content.lower()
            if 'human' in content_lower and 'likely' in content_lower:
                return 15.0
            elif 'ai-generated' in content_lower or 'generated by ai' in content_lower:
                return 80.0
            
            raise Exception("Could not extract percentage from results")
            
        except Exception as e:
            raise Exception(f"Error extracting Writer results: {e}")
